### ISSUE TITLE
contact form

### ISSUE THREAD

**Issue by PcGamer49** [Danack/PHP-to-Javascript#68]
Hello, I have a question, it is also possible to use a contact form to convert javascript, who can help me please

With friendly greetings

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Contacteer ons - KMO</title>
    
    <link href="css/style.css" rel="stylesheet">
    
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700' rel='stylesheet' type='text/css'>
    
  </head>
  <body>
      
    <div class="content">
      <h1>Contact</h1>
      <p>Do you have a specific question, do you want more information
         or do you want a free visit from a representative
         please fill in the information below. We will soon contact.</p>
    </div>
    	       <form method="post" role="form" action="send.php">
              <div class="form-group">
                <label>Uw naam</label>
                <input type="text" name="name" class="form-control" id="exampleInputName1" placeholder="Enter your name">
              </div>
              <div class="form-group">
                <label>Uw email</label>
                <input type="email" name="email" class="form-control" id="exampleInputEmail1" placeholder="Enter your email address">
              </div>
              <div class="form-group">
                <label>Uw bericht</label>
                <textarea name="vraag" class="form-control" rows="3" placeholder="Enter your message"></textarea>
              </div>
              <button type="submit" class="btn-primary">Send your message
</button>
             </form>
    
  </body>
</html>

<?php
$naam = $_POST['name'];
$email = $_POST['email'];
$vraag = $_POST['demand'];

$formcontent=" Van: $name \n Email: $email \n demand: $demand";
$recipient = "test@pi.be";
$subject = "Contact Formulier Website";
$mailheader = "From: $email \r\n";
mail($recipient, $subject, $formcontent, $mailheader) or die("Error!");
header("Location: thanks.php");
?>

**Comment by Danack** [comment]
Hi @PcGamer49,

Really, the only thing this library should ever be used for (and even then it's dubious) is converting trvially simple objects and functions to Javascript.

It doesn't sound like that would fit your use-case.

cheers
Dan
